language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r mediate-springboot2-webservice *
  - mkdir -p deploy
  - mv mediate-springboot2-webservice.zip deploy/mediate-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: mediate-springboot-build #s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - arsgsg1@gmail.com