spring:
  config:
    activate:
      on-profile: local-secret

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 864000000

firebase:
  config-path: firebase/firebase_service_key.json
  api-url: https://fcm.googleapis.com/v1/projects/mediate-e9a59/messages:send
---
spring:
  config:
    activate:
      on-profile: test-aws

cloud:
  aws:
    credentials:
      access-key: MoCkinGPassWord
      secret-key: MoCkinGPassWord
    region:
      static: ap-northeast-2
    s3:
      bucket: mediate-article-image
    stack:
      auto: false