spring:
  profiles:
    group:
      local: local-db, local-secret
      local-maria: local-maria, local-secret
      prod1: prod, prod-db, prod-secret
      prod2: prod, prod-db, prod-secret
      test: local-secret