spring:
  config:
    activate:
      on-profile: local-maria

  datasource:
    url: jdbc:mariadb://localhost:3308/mediate
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: com.ko.mediate.HC.common.Infra.CustomMysqlDialect
  decorator:
    datasource:
      p6spy.enable-logging: false