jwt:
  header: Authorization
  #로컬 테스트용 더미 값
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access:
    expired-time: 3600000 #60분
  refresh:
    expired-time: 604800000 #7일
firebase:
  config-path: firebase/firebase_service_key.json
  api-url: https://fcm.googleapis.com/v1/projects/mediate-e9a59/messages:send