spring:
  profiles:
    group:
      local: local-h2
      test: local-h2
      prod1: prod-db
      prod2: prod-db
    include:
      - aws
      - secret
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
image:
  convert-path: '${user.dir}'
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: prod1
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod2
server:
  port: 8082