spring:
  profiles:
    group:
      local: local-h2
      test: local-h2
      prod1: prod-db
      prod2: prod-db
    include:
      - aws
      - secret
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
image:
  convert-path: '${user.dir}'
oauth2:
  client:
    google:
      base-url: https://www.googleapis.com
      path: /oauth2/v2/userinfo
    kakao:
      base-url: https://kapi.kakao.com
      path: /v2/user/me
    naver:
      base-url: https://openapi.naver.com
      path: /v1/nid/me
---
spring:
  config:
    activate:
      on-profile: prod1
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod2
server:
  port: 8082